task1 has been done
NataliaStekolnikova/tasks pull request #1
Opened 2023-05-20 20:07 UTC by NataliaStekolnikova

Closes task1

2023-05-24 11:06 UTC, a-kosak-mbx requested changes

2023-05-24 11:06 UTC, a-kosak-mbx commented on tasks/task_1.py
> +# Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.
Зачем вот это вот все?

2023-05-24 11:06 UTC, a-kosak-mbx commented on tasks/task_1.py
> +#    return ..., ..., ...
Можно не комментировать, а просто сразу же здесь и писать.

2023-05-24 11:06 UTC, a-kosak-mbx commented on tasks/task_1.py
> +    difference = first - second
Вот это все лишнее. Лучше делать в одну строчку.
Зачем вам все эти промежуточные вычисления, которые не несут в себе никакого смысла?

2023-05-24 11:06 UTC, a-kosak-mbx commented on tasks/task_1.py
> +    remainder = first % second
То же самое - лишние промежуточные вычисления и временные переменные.
Да и в целом не нужно комментировать каждую строчку. Все и так понятно же, что делает каждая строка.

2023-05-24 11:06 UTC, a-kosak-mbx commented on tasks/task_1.py
> +    return (value << 1, value << 3, value << 5)
Круглые скобки лишние.

2023-05-24 11:06 UTC, a-kosak-mbx commented on tasks/task_1.py
> +    return (value >> 1, value >> 3, value >> 5)
Круглые скобки лишние.

2023-05-24 11:06 UTC, a-kosak-mbx commented on tasks/task_1.py
> +    remainder = divident % divider
Лишняя промежуточная операция, лучше в одну строку записать.

2023-05-24 11:06 UTC, a-kosak-mbx commented on tasks/task_1.py
> +        return "negative"
В целом все правильно, но вот что это такое? Разве было где-то указано, что нужно выводить в виде строки результат? Он указан как int. Соответственно -1 для отрицательных, 0 для нуля и +1 для положительных.

2023-05-24 11:06 UTC, a-kosak-mbx commented on tasks/task_1.py
> +        return "negative"
Вот это вот else лишнее, просто return.

2023-05-24 11:06 UTC, a-kosak-mbx commented on tasks/task_1.py
> +    return (~value + 1)
Круглые скобки лишние.

2023-05-24 11:06 UTC, a-kosak-mbx commented on tasks/task_1.py
> +    return bin(value).count('0')  # вычитаем 1, так как самый левый бит всегда равен 0
Неправильно. Просто подставьте, например, 13 и посмотрите на результат.

2023-05-24 11:06 UTC, a-kosak-mbx commented on tasks/task_1.py
> +    elif value > high:
Просто if.

2023-05-24 11:06 UTC, a-kosak-mbx commented on tasks/task_1.py
> +    else:
Else лишнее. Просто return.

2023-05-24 11:06 UTC, a-kosak-mbx commented on tasks/task_1.py
> +        return None
Сказано ведь, что нижняя граница может быть как больше, так и меньше.

2023-05-24 11:06 UTC, a-kosak-mbx commented on tasks/task_1.py
> +        return value
Почему бы не воспользоваться написанной ранее функцией? Зачем дублировать код?

2023-05-24 11:06 UTC, a-kosak-mbx commented on tasks/task_1.py
> +        return False
Зачем вы возвращаете True, когда условие равно True и False, если условие равно False? Это разве не абсурдно? Почему бы не возвратить сразу условие?

2023-05-24 11:06 UTC, a-kosak-mbx commented on tasks/task_1.py
> +    return ((value + 0.25) * 0.5) ** 0.25
Мало того, что не 0.25, а 4, так по заданию нужно было просто расставить скобки, а не менять что-то местами.

2023-05-24 11:06 UTC, a-kosak-mbx commented on tasks/task_1.py
> +    mask = 1 << n
Лишние промежуточные вычисления.

2023-05-24 11:06 UTC, a-kosak-mbx commented on tasks/task_1.py
> +    mask = 1 << n
Лишние промежуточные вычисления.

2023-05-24 11:06 UTC, a-kosak-mbx commented on tasks/task_1.py
> +
Вот это все можно было не делать.

2023-05-24 11:06 UTC, a-kosak-mbx commented on tasks/task_1.py
> +# Press the green button in the gutter to run the script.
К чему относиться этот комментарий?

2023-05-24 11:06 UTC, a-kosak-mbx commented on tasks/task_1.py
> +#    return ...
Правильно понимаю, что эта задача не решена?

2023-05-24 11:06 UTC, a-kosak-mbx commented on tasks/task_1.py
> +#    return ...
Правильно понимаю, что эта задача не решена?

2023-06-18 15:39 UTC, a-kosak-mbx approved these changes
Неплохо. Замените только clamp_any еще. И можно мержить.

2023-06-18 15:39 UTC, a-kosak-mbx commented on tasks/task_1.py
> +    return value
Можно было использовать функцию `clamp`, вы ведь уже ее написали, зачем копипастить.

2023-06-26 00:18 UTC, NataliaStekolnikova commented on tasks/task_1.py
> +#    return ...
да, она дополнительная, и повышенной сложности

2023-06-26 00:18 UTC, NataliaStekolnikova commented on tasks/task_1.py
> +#    return ...
да, она дополнительная, и повышенной сложности

2023-06-26 00:19 UTC, NataliaStekolnikova commented on tasks/task_1.py
> +# Press the green button in the gutter to run the script.
такие комментарии будут удалены

2023-06-29 19:34 UTC, merged